[colors]
draw_bold_text_with_bright_colors = true

# Colors (Tokyo Night)
# Source: https://github.com/zatchheems/tokyo-night-alacritty-theme

# Bright colors
[colors.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x0db9d7"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xacb0d0"
yellow = "0xff9e64"

# Normal colors
[colors.normal]
black = "0x32344a"
blue = "0x7aa2f7"
cyan = "0x449dab"
green = "0x9ece6a"
magenta = "0xad8ee6"
red = "0xf7768e"
white = "0x787c99"
yellow = "0xe0af68"

# Default colors
[colors.primary]
background = "0x1a1b26"
foreground = "0xa9b1d6"

[font]
size = 11

[font.normal]
family = "Hack Nerd Font Mono"

[font.offset]
x = 1
y = 1

[window]
opacity = 0.9

[window.padding]
x = 5
y = 5
